### ISSUE TITLE
hls video playback on mobile

### ISSUE THREAD

**Issue by drewvivid** [ApiVideo/php-sdk#6]
hey team, loving the API - I have a question about video playback on mobile.

I'm using the hls.js library to embed videos as suggested, which works fine on a desktop browser, but safari and chrome on iOS will not play the videos.

I will test the iframe option but I wonder if you have any other direct embed links that we could use that would work in a standard HTML5 video tag?

<video controls>
  <src="https://api.video/xxxxxxx"
</video>

**Comment by ApiVideo** [comment]
Hi,

Do you followed this part of documentation: https://docs.api.video/5.1/vod-tutorial/embed-videos

**Comment by drewvivid** [comment]
I did, had a few troubles, ended up changing to a different provider though
so I'm not using API.video anymore
